import { GenerateRecipeFromPantryOutput } from '@/ai/flows/generate-recipe-from-pantry';
import { AnalyzeRecipeNutritionOutput } from '@/ai/flows/analyze-recipe-nutrition-flow';

export type Recipe = GenerateRecipeFromPantryOutput & {
  id: string;
  nutrition?: AnalyzeRecipeNutritionOutput;
  imageUrl?: string;
  savedAt?: number;
};

export type Ingredient = {
  name: string;
  category: string;
};

export const COMMON_INGREDIENTS: Ingredient[] = [
  // Pantry Essentials
  { name: 'All-Purpose Flour', category: 'Pantry' },
  { name: 'White Rice', category: 'Pantry' },
  { name: 'Brown Rice', category: 'Pantry' },
  { name: 'Quinoa', category: 'Pantry' },
  { name: 'Pasta', category: 'Pantry' },
  { name: 'Rolled Oats', category: 'Pantry' },
  { name: 'Sugar', category: 'Pantry' },
  { name: 'Brown Sugar', category: 'Pantry' },
  { name: 'Honey', category: 'Pantry' },
  { name: 'Maple Syrup', category: 'Pantry' },
  { name: 'Baking Powder', category: 'Pantry' },
  { name: 'Baking Soda', category: 'Pantry' },
  { name: 'Cornstarch', category: 'Pantry' },
  { name: 'Breadcrumbs', category: 'Pantry' },
  
  // Oils & Vinegars
  { name: 'Olive Oil', category: 'Oils & Vinegars' },
  { name: 'Vegetable Oil', category: 'Oils & Vinegars' },
  { name: 'Sesame Oil', category: 'Oils & Vinegars' },
  { name: 'Coconut Oil', category: 'Oils & Vinegars' },
  { name: 'Balsamic Vinegar', category: 'Oils & Vinegars' },
  { name: 'Apple Cider Vinegar', category: 'Oils & Vinegars' },
  { name: 'Rice Vinegar', category: 'Oils & Vinegars' },
  { name: 'Red Wine Vinegar', category: 'Oils & Vinegars' },

  // Fridge & Dairy
  { name: 'Milk', category: 'Dairy' },
  { name: 'Heavy Cream', category: 'Dairy' },
  { name: 'Butter', category: 'Dairy' },
  { name: 'Eggs', category: 'Fridge' },
  { name: 'Greek Yogurt', category: 'Dairy' },
  { name: 'Cheddar Cheese', category: 'Dairy' },
  { name: 'Parmesan Cheese', category: 'Dairy' },
  { name: 'Mozzarella', category: 'Dairy' },
  { name: 'Feta Cheese', category: 'Dairy' },
  { name: 'Cream Cheese', category: 'Dairy' },
  { name: 'Tofu', category: 'Fridge' },
  
  // Vegetables
  { name: 'Onion', category: 'Vegetables' },
  { name: 'Garlic', category: 'Vegetables' },
  { name: 'Ginger', category: 'Vegetables' },
  { name: 'Potato', category: 'Vegetables' },
  { name: 'Sweet Potato', category: 'Vegetables' },
  { name: 'Carrot', category: 'Vegetables' },
  { name: 'Bell Pepper', category: 'Vegetables' },
  { name: 'Broccoli', category: 'Vegetables' },
  { name: 'Spinach', category: 'Vegetables' },
  { name: 'Kale', category: 'Vegetables' },
  { name: 'Zucchini', category: 'Vegetables' },
  { name: 'Tomato', category: 'Vegetables' },
  { name: 'Cucumber', category: 'Vegetables' },
  { name: 'Celery', category: 'Vegetables' },
  { name: 'Asparagus', category: 'Vegetables' },
  { name: 'Eggplant', category: 'Vegetables' },
  { name: 'Avocado', category: 'Vegetables' },
  { name: 'Cauliflower', category: 'Vegetables' },
  { name: 'Green Beans', category: 'Vegetables' },
  { name: 'Cabbage', category: 'Vegetables' },
  { name: 'Artichoke', category: 'Vegetables' },
  { name: 'Arugula', category: 'Vegetables' },
  { name: 'Bamboo Shoots', category: 'Vegetables' },
  { name: 'Bok Choy', category: 'Vegetables' },
  { name: 'Brussels Sprouts', category: 'Vegetables' },
  { name: 'Butternut Squash', category: 'Vegetables' },
  { name: 'Chard', category: 'Vegetables' },
  { name: 'Collard Greens', category: 'Vegetables' },
  { name: 'Corn', category: 'Vegetables' },
  { name: 'Daikon', category: 'Vegetables' },
  { name: 'Fennel', category: 'Vegetables' },
  { name: 'Jicama', category: 'Vegetables' },
  { name: 'Kohlrabi', category: 'Vegetables' },
  { name: 'Leek', category: 'Vegetables' },
  { name: 'Okra', category: 'Vegetables' },
  { name: 'Parsnip', category: 'Vegetables' },
  { name: 'Peas', category: 'Vegetables' },
  { name: 'Pumpkin', category: 'Vegetables' },
  { name: 'Radish', category: 'Vegetables' },
  { name: 'Rutabaga', category: 'Vegetables' },
  { name: 'Shallot', category: 'Vegetables' },
  { name: 'Snow Peas', category: 'Vegetables' },
  { name: 'Sugar Snap Peas', category: 'Vegetables' },
  { name: 'Turnip', category: 'Vegetables' },
  { name: 'Water Chestnuts', category: 'Vegetables' },
  { name: 'Watercress', category: 'Vegetables' },
  { name: 'Yam', category: 'Vegetables' },
  { name: 'Acorn Squash', category: 'Vegetables' },
  { name: 'Beets', category: 'Vegetables' },
  { name: 'Endive', category: 'Vegetables' },
  { name: 'Escarole', category: 'Vegetables' },
  { name: 'Frisée', category: 'Vegetables' },
  { name: 'Jerusalem Artichoke', category: 'Vegetables' },
  { name: 'Lotus Root', category: 'Vegetables' },
  { name: 'Microgreens', category: 'Vegetables' },
  { name: 'Napa Cabbage', category: 'Vegetables' },
  { name: 'Radicchio', category: 'Vegetables' },
  { name: 'Rhubarb', category: 'Vegetables' },
  { name: 'Spaghetti Squash', category: 'Vegetables' },
  { name: 'Sunchokes', category: 'Vegetables' },
  { name: 'Tomatillo', category: 'Vegetables' },
  { name: 'Shiitake', category: 'Vegetables' },
  { name: 'Oyster Mushroom', category: 'Vegetables' },
  { name: 'Enoki', category: 'Vegetables' },
  { name: 'Portobello', category: 'Vegetables' },

  // Spicy Vegetables (Chilies)
  { name: 'Jalapeño Pepper', category: 'Vegetables' },
  { name: 'Habanero Pepper', category: 'Vegetables' },
  { name: 'Serrano Pepper', category: 'Vegetables' },
  { name: 'Thai Bird\'s Eye Chili', category: 'Vegetables' },
  { name: 'Scotch Bonnet', category: 'Vegetables' },
  { name: 'Ghost Pepper (Bhut Jolokia)', category: 'Vegetables' },
  { name: 'Carolina Reaper', category: 'Vegetables' },
  { name: 'Anaheim Pepper', category: 'Vegetables' },
  { name: 'Poblano Pepper', category: 'Vegetables' },
  { name: 'Shishito Pepper', category: 'Vegetables' },
  { name: 'Fresno Chili', category: 'Vegetables' },
  { name: 'Bird\'s Eye Chili', category: 'Vegetables' },
  { name: 'Tabasco Pepper', category: 'Vegetables' },
  { name: 'Cayenne Pepper (Fresh)', category: 'Vegetables' },
  { name: 'Manzano Pepper', category: 'Vegetables' },
  { name: 'Rocoto Pepper', category: 'Vegetables' },
  { name: 'Peri-Peri Chili', category: 'Vegetables' },
  { name: 'Naga Viper', category: 'Vegetables' },
  { name: 'Trinidad Scorpion', category: 'Vegetables' },
  { name: 'Padron Pepper', category: 'Vegetables' },
  { name: 'Aji Amarillo', category: 'Vegetables' },
  { name: 'Aji Dulce', category: 'Vegetables' },
  { name: 'Cherry Bomb Pepper', category: 'Vegetables' },
  { name: 'Long Red Chili', category: 'Vegetables' },
  { name: 'Hot Green Chili', category: 'Vegetables' },

  // Fruits
  { name: 'Lemon', category: 'Fruit' },
  { name: 'Lime', category: 'Fruit' },
  { name: 'Orange', category: 'Fruit' },
  { name: 'Apple', category: 'Fruit' },
  { name: 'Banana', category: 'Fruit' },
  { name: 'Blueberries', category: 'Fruit' },
  { name: 'Strawberries', category: 'Fruit' },
  { name: 'Pineapple', category: 'Fruit' },
  { name: 'Mango', category: 'Fruit' },

  // Proteins
  { name: 'Chicken Breast', category: 'Meat' },
  { name: 'Chicken Thighs', category: 'Meat' },
  { name: 'Ground Beef', category: 'Meat' },
  { name: 'Steak', category: 'Meat' },
  { name: 'Pork Chops', category: 'Meat' },
  { name: 'Bacon', category: 'Meat' },
  { name: 'Salmon', category: 'Seafood' },
  { name: 'Shrimp', category: 'Seafood' },
  { name: 'Canned Tuna', category: 'Seafood' },
  { name: 'White Fish', category: 'Seafood' },

  // Spices & Powders (including spicy ones)
  { name: 'Salt', category: 'Spices' },
  { name: 'Black Pepper', category: 'Spices' },
  { name: 'Cinnamon', category: 'Spices' },
  { name: 'Cumin', category: 'Spices' },
  { name: 'Paprika', category: 'Spices' },
  { name: 'Turmeric', category: 'Spices' },
  { name: 'Chili Powder', category: 'Spices' },
  { name: 'Garlic Powder', category: 'Spices' },
  { name: 'Onion Powder', category: 'Spices' },
  { name: 'Cayenne Powder', category: 'Spices' },
  { name: 'Crushed Red Pepper Flakes', category: 'Spices' },
  { name: 'Gochugaru (Korean Chili Flakes)', category: 'Spices' },
  { name: 'Aleppo Pepper', category: 'Spices' },
  { name: 'Ancho Chili Powder', category: 'Spices' },
  { name: 'Chipotle Powder', category: 'Spices' },
  { name: 'Guajillo Chili Powder', category: 'Spices' },
  { name: 'Smoked Hot Paprika', category: 'Spices' },
  { name: 'Berbere', category: 'Spices' },
  { name: 'Togarashi (Shichimi)', category: 'Spices' },
  { name: 'Wasabi Powder', category: 'Spices' },
  { name: 'Mustard Powder (Hot)', category: 'Spices' },
  { name: 'Sichuan Peppercorns', category: 'Spices' },
  { name: 'White Pepper', category: 'Spices' },
  { name: 'Harissa Powder', category: 'Spices' },
  { name: 'Piri Piri Seasoning', category: 'Spices' },
  { name: 'Jerk Seasoning', category: 'Spices' },
  { name: 'Cajun Seasoning', category: 'Spices' },
  { name: 'Long Pepper', category: 'Spices' },
  { name: 'Sriracha Powder', category: 'Spices' },

  // Herbs
  { name: 'Fresh Cilantro', category: 'Herbs' },
  { name: 'Fresh Parsley', category: 'Herbs' },
  { name: 'Fresh Basil', category: 'Herbs' },
  { name: 'Fresh Rosemary', category: 'Herbs' },
  { name: 'Fresh Thyme', category: 'Herbs' },

  // Legumes & Nuts
  { name: 'Chickpeas', category: 'Legumes' },
  { name: 'Black Beans', category: 'Legumes' },
  { name: 'Lentils', category: 'Legumes' },
  { name: 'Kidney Beans', category: 'Legumes' },
  { name: 'Peanut Butter', category: 'Pantry' },
  { name: 'Almonds', category: 'Nuts' },
  { name: 'Walnuts', category: 'Nuts' },
  { name: 'Cashews', category: 'Nuts' },

  // Sauces & Condiments (including spicy ones)
  { name: 'Soy Sauce', category: 'Sauces' },
  { name: 'Mayonnaise', category: 'Sauces' },
  { name: 'Mustard', category: 'Sauces' },
  { name: 'Ketchup', category: 'Sauces' },
  { name: 'Hot Sauce (Tabasco)', category: 'Sauces' },
  { name: 'Sriracha', category: 'Sauces' },
  { name: 'Miso Paste', category: 'Sauces' },
  { name: 'Tomato Paste', category: 'Sauces' },
  { name: 'Gochujang', category: 'Sauces' },
  { name: 'Sambal Oelek', category: 'Sauces' },
  { name: 'Harissa Paste', category: 'Sauces' },
  { name: 'Szechuan Chili Oil', category: 'Sauces' },
  { name: 'Chili Crisp (Lao Gan Ma)', category: 'Sauces' },
  { name: 'Peri Peri Sauce', category: 'Sauces' },
  { name: 'Buffalo Sauce', category: 'Sauces' },
  { name: 'Thai Sweet Chili Sauce', category: 'Sauces' },
  { name: 'Nam Prik Pao', category: 'Sauces' },
  { name: 'Kimchi Base', category: 'Sauces' },
  { name: 'Horseradish Sauce', category: 'Sauces' },
  { name: 'Wasabi Paste', category: 'Sauces' },
  { name: 'Adobo Sauce', category: 'Sauces' },
  { name: 'Mole Poblano Sauce', category: 'Sauces' },
  { name: 'Chili Garlic Sauce', category: 'Sauces' },
  { name: 'Green Chili Sauce', category: 'Sauces' },
  { name: 'Chipotle in Adobo', category: 'Sauces' },
  { name: 'Coconut Milk', category: 'Pantry' },
  { name: 'Chicken Broth', category: 'Pantry' },
];
