import { GenerateRecipeFromPantryOutput } from '@/ai/flows/generate-recipe-from-pantry';
import { AnalyzeRecipeNutritionOutput } from '@/ai/flows/analyze-recipe-nutrition-flow';

export type Recipe = GenerateRecipeFromPantryOutput & {
  id: string;
  nutrition?: AnalyzeRecipeNutritionOutput;
  imageUrl?: string;
  savedAt?: number;
};

export type Ingredient = {
  name: string;
  category: string;
};

export const COMMON_INGREDIENTS: Ingredient[] = [
  // Pantry Essentials
  { name: 'All-Purpose Flour', category: 'Pantry' },
  { name: 'White Rice', category: 'Pantry' },
  { name: 'Brown Rice', category: 'Pantry' },
  { name: 'Quinoa', category: 'Pantry' },
  { name: 'Pasta', category: 'Pantry' },
  { name: 'Rolled Oats', category: 'Pantry' },
  { name: 'Sugar', category: 'Pantry' },
  { name: 'Brown Sugar', category: 'Pantry' },
  { name: 'Honey', category: 'Pantry' },
  { name: 'Maple Syrup', category: 'Pantry' },
  { name: 'Baking Powder', category: 'Pantry' },
  { name: 'Baking Soda', category: 'Pantry' },
  { name: 'Cornstarch', category: 'Pantry' },
  { name: 'Breadcrumbs', category: 'Pantry' },
  
  // Oils & Vinegars
  { name: 'Olive Oil', category: 'Oils & Vinegars' },
  { name: 'Vegetable Oil', category: 'Oils & Vinegars' },
  { name: 'Sesame Oil', category: 'Oils & Vinegars' },
  { name: 'Coconut Oil', category: 'Oils & Vinegars' },
  { name: 'Balsamic Vinegar', category: 'Oils & Vinegars' },
  { name: 'Apple Cider Vinegar', category: 'Oils & Vinegars' },
  { name: 'Rice Vinegar', category: 'Oils & Vinegars' },
  { name: 'Red Wine Vinegar', category: 'Oils & Vinegars' },

  // Fridge & Dairy
  { name: 'Milk', category: 'Dairy' },
  { name: 'Heavy Cream', category: 'Dairy' },
  { name: 'Butter', category: 'Dairy' },
  { name: 'Eggs', category: 'Fridge' },
  { name: 'Greek Yogurt', category: 'Dairy' },
  { name: 'Cheddar Cheese', category: 'Dairy' },
  { name: 'Parmesan Cheese', category: 'Dairy' },
  { name: 'Mozzarella', category: 'Dairy' },
  { name: 'Feta Cheese', category: 'Dairy' },
  { name: 'Cream Cheese', category: 'Dairy' },
  { name: 'Tofu', category: 'Fridge' },
  
  // Vegetables (The Global Master List)
  { name: 'Onion', category: 'Vegetables' },
  { name: 'Garlic', category: 'Vegetables' },
  { name: 'Ginger', category: 'Vegetables' },
  { name: 'Potato', category: 'Vegetables' },
  { name: 'Sweet Potato', category: 'Vegetables' },
  { name: 'Carrot', category: 'Vegetables' },
  { name: 'Bell Pepper', category: 'Vegetables' },
  { name: 'Broccoli', category: 'Vegetables' },
  { name: 'Spinach', category: 'Vegetables' },
  { name: 'Kale', category: 'Vegetables' },
  { name: 'Zucchini', category: 'Vegetables' },
  { name: 'Tomato', category: 'Vegetables' },
  { name: 'Cucumber', category: 'Vegetables' },
  { name: 'Celery', category: 'Vegetables' },
  { name: 'Asparagus', category: 'Vegetables' },
  { name: 'Eggplant', category: 'Vegetables' },
  { name: 'Avocado', category: 'Vegetables' },
  { name: 'Cauliflower', category: 'Vegetables' },
  { name: 'Green Beans', category: 'Vegetables' },
  { name: 'Cabbage', category: 'Vegetables' },
  { name: 'Artichoke', category: 'Vegetables' },
  { name: 'Arugula', category: 'Vegetables' },
  { name: 'Bamboo Shoots', category: 'Vegetables' },
  { name: 'Bok Choy', category: 'Vegetables' },
  { name: 'Brussels Sprouts', category: 'Vegetables' },
  { name: 'Butternut Squash', category: 'Vegetables' },
  { name: 'Chard', category: 'Vegetables' },
  { name: 'Collard Greens', category: 'Vegetables' },
  { name: 'Corn', category: 'Vegetables' },
  { name: 'Daikon', category: 'Vegetables' },
  { name: 'Fennel', category: 'Vegetables' },
  { name: 'Jicama', category: 'Vegetables' },
  { name: 'Kohlrabi', category: 'Vegetables' },
  { name: 'Leek', category: 'Vegetables' },
  { name: 'Okra', category: 'Vegetables' },
  { name: 'Parsnip', category: 'Vegetables' },
  { name: 'Peas', category: 'Vegetables' },
  { name: 'Pumpkin', category: 'Vegetables' },
  { name: 'Radish', category: 'Vegetables' },
  { name: 'Rutabaga', category: 'Vegetables' },
  { name: 'Shallot', category: 'Vegetables' },
  { name: 'Snow Peas', category: 'Vegetables' },
  { name: 'Sugar Snap Peas', category: 'Vegetables' },
  { name: 'Turnip', category: 'Vegetables' },
  { name: 'Water Chestnuts', category: 'Vegetables' },
  { name: 'Watercress', category: 'Vegetables' },
  { name: 'Yam', category: 'Vegetables' },
  { name: 'Acorn Squash', category: 'Vegetables' },
  { name: 'Beets', category: 'Vegetables' },
  { name: 'Endive', category: 'Vegetables' },
  { name: 'Escarole', category: 'Vegetables' },
  { name: 'Frisée', category: 'Vegetables' },
  { name: 'Jerusalem Artichoke', category: 'Vegetables' },
  { name: 'Lotus Root', category: 'Vegetables' },
  { name: 'Microgreens', category: 'Vegetables' },
  { name: 'Napa Cabbage', category: 'Vegetables' },
  { name: 'Radicchio', category: 'Vegetables' },
  { name: 'Rhubarb', category: 'Vegetables' },
  { name: 'Spaghetti Squash', category: 'Vegetables' },
  { name: 'Sunchokes', category: 'Vegetables' },
  { name: 'Tomatillo', category: 'Vegetables' },
  { name: 'Bitter Melon', category: 'Vegetables' },
  { name: 'Winter Melon', category: 'Vegetables' },
  { name: 'Chayote', category: 'Vegetables' },
  { name: 'Taro', category: 'Vegetables' },
  { name: 'Cassava', category: 'Vegetables' },
  { name: 'Burdock Root', category: 'Vegetables' },
  { name: 'Fresh Galangal', category: 'Vegetables' },
  { name: 'Fresh Turmeric', category: 'Vegetables' },
  { name: 'Horseradish', category: 'Vegetables' },
  { name: 'Celeriac', category: 'Vegetables' },
  { name: 'Parsley Root', category: 'Vegetables' },
  { name: 'Salsify', category: 'Vegetables' },
  { name: 'Water Spinach', category: 'Vegetables' },
  { name: 'Gai Lan', category: 'Vegetables' },
  { name: 'Yu Choy', category: 'Vegetables' },
  { name: 'Mizuna', category: 'Vegetables' },
  { name: 'Tatsoi', category: 'Vegetables' },
  { name: 'Sorrel', category: 'Vegetables' },
  { name: 'Purslane', category: 'Vegetables' },
  { name: 'Nori', category: 'Vegetables' },
  { name: 'Wakame', category: 'Vegetables' },
  { name: 'Kombu', category: 'Vegetables' },
  { name: 'Dulse', category: 'Vegetables' },
  { name: 'Fiddlehead Ferns', category: 'Vegetables' },
  { name: 'Hearts of Palm', category: 'Vegetables' },
  { name: 'Cardoon', category: 'Vegetables' },
  { name: 'Ramps', category: 'Vegetables' },
  { name: 'Garlic Scapes', category: 'Vegetables' },
  { name: 'Squash Blossoms', category: 'Vegetables' },
  { name: 'Pea Shoots', category: 'Vegetables' },
  { name: 'Sunflower Shoots', category: 'Vegetables' },
  { name: 'Oca', category: 'Vegetables' },
  { name: 'Ulluco', category: 'Vegetables' },
  { name: 'Mashua', category: 'Vegetables' },
  { name: 'Arracacha', category: 'Vegetables' },
  { name: 'Samphire', category: 'Vegetables' },
  { name: 'Sea Kale', category: 'Vegetables' },
  { name: 'Romanesco', category: 'Vegetables' },
  { name: 'Broccolini', category: 'Vegetables' },
  { name: 'Broccoli Rabe', category: 'Vegetables' },
  { name: 'Savoy Cabbage', category: 'Vegetables' },
  { name: 'Red Cabbage', category: 'Vegetables' },
  { name: 'Mustard Greens', category: 'Vegetables' },
  { name: 'Turnip Greens', category: 'Vegetables' },
  { name: 'Beet Greens', category: 'Vegetables' },
  { name: 'Dandelion Greens', category: 'Vegetables' },
  { name: 'Stinging Nettle', category: 'Vegetables' },
  { name: 'Malabar Spinach', category: 'Vegetables' },
  { name: 'Amaranth Leaves', category: 'Vegetables' },
  { name: 'Lambs Quarters', category: 'Vegetables' },
  { name: 'Fat Hen', category: 'Vegetables' },
  { name: 'Chickweed', category: 'Vegetables' },
  { name: 'Miner\'s Lettuce', category: 'Vegetables' },
  { name: 'Bottle Gourd', category: 'Vegetables' },
  { name: 'Snake Gourd', category: 'Vegetables' },
  { name: 'Ivy Gourd', category: 'Vegetables' },
  { name: 'Ash Gourd', category: 'Vegetables' },
  { name: 'Spiny Gourd', category: 'Vegetables' },
  { name: 'Tindora', category: 'Vegetables' },
  { name: 'Moringa (Drumstick)', category: 'Vegetables' },
  { name: 'Winged Bean', category: 'Vegetables' },
  { name: 'Long Bean', category: 'Vegetables' },
  { name: 'Fava Bean', category: 'Vegetables' },
  { name: 'Lima Bean', category: 'Vegetables' },
  { name: 'Skirret', category: 'Vegetables' },
  { name: 'Scorzonera', category: 'Vegetables' },
  { name: 'Hamburg Parsley', category: 'Vegetables' },
  { name: 'Water Caltrop', category: 'Vegetables' },
  { name: 'Lotus Seed', category: 'Vegetables' },
  { name: 'Ginkgo Nut', category: 'Vegetables' },
  { name: 'Wild Garlic', category: 'Vegetables' },
  { name: 'Elephant Garlic', category: 'Vegetables' },
  { name: 'Tree Onion', category: 'Vegetables' },
  { name: 'Garlic Chives', category: 'Vegetables' },
  { name: 'Crosne (Chinese Artichoke)', category: 'Vegetables' },
  { name: 'Yacon', category: 'Vegetables' },
  { name: 'Tigernut', category: 'Vegetables' },
  { name: 'Jicama (already in list)', category: 'Vegetables' },
  
  // Mushrooms
  { name: 'Shiitake', category: 'Vegetables' },
  { name: 'Oyster Mushroom', category: 'Vegetables' },
  { name: 'Enoki', category: 'Vegetables' },
  { name: 'Shimeji', category: 'Vegetables' },
  { name: 'King Trumpet', category: 'Vegetables' },
  { name: 'Maitake', category: 'Vegetables' },
  { name: 'Porcini', category: 'Vegetables' },
  { name: 'Chanterelle', category: 'Vegetables' },
  { name: 'Morel', category: 'Vegetables' },
  { name: 'Wood Ear', category: 'Vegetables' },
  { name: 'Lion\'s Mane', category: 'Vegetables' },
  { name: 'Portobello', category: 'Vegetables' },
  { name: 'Cremini', category: 'Vegetables' },
  { name: 'Button Mushroom', category: 'Vegetables' },

  // Fruits
  { name: 'Lemon', category: 'Fruit' },
  { name: 'Lime', category: 'Fruit' },
  { name: 'Orange', category: 'Fruit' },
  { name: 'Apple', category: 'Fruit' },
  { name: 'Banana', category: 'Fruit' },
  { name: 'Blueberries', category: 'Fruit' },
  { name: 'Strawberries', category: 'Fruit' },
  { name: 'Pineapple', category: 'Fruit' },
  { name: 'Mango', category: 'Fruit' },

  // Proteins
  { name: 'Chicken Breast', category: 'Meat' },
  { name: 'Chicken Thighs', category: 'Meat' },
  { name: 'Ground Beef', category: 'Meat' },
  { name: 'Steak', category: 'Meat' },
  { name: 'Pork Chops', category: 'Meat' },
  { name: 'Bacon', category: 'Meat' },
  { name: 'Salmon', category: 'Seafood' },
  { name: 'Shrimp', category: 'Seafood' },
  { name: 'Canned Tuna', category: 'Seafood' },
  { name: 'White Fish', category: 'Seafood' },

  // Spices & Herbs
  { name: 'Salt', category: 'Spices' },
  { name: 'Black Pepper', category: 'Spices' },
  { name: 'Cinnamon', category: 'Spices' },
  { name: 'Cumin', category: 'Spices' },
  { name: 'Paprika', category: 'Spices' },
  { name: 'Turmeric', category: 'Spices' },
  { name: 'Chili Powder', category: 'Spices' },
  { name: 'Dried Oregano', category: 'Spices' },
  { name: 'Dried Thyme', category: 'Spices' },
  { name: 'Dried Basil', category: 'Spices' },
  { name: 'Garlic Powder', category: 'Spices' },
  { name: 'Onion Powder', category: 'Spices' },
  { name: 'Cayenne Pepper', category: 'Spices' },
  { name: 'Fresh Cilantro', category: 'Herbs' },
  { name: 'Fresh Parsley', category: 'Herbs' },
  { name: 'Fresh Basil', category: 'Herbs' },
  { name: 'Fresh Rosemary', category: 'Herbs' },
  { name: 'Fresh Thyme', category: 'Herbs' },

  // Legumes & Nuts
  { name: 'Chickpeas', category: 'Legumes' },
  { name: 'Black Beans', category: 'Legumes' },
  { name: 'Lentils', category: 'Legumes' },
  { name: 'Kidney Beans', category: 'Legumes' },
  { name: 'Peanut Butter', category: 'Pantry' },
  { name: 'Almonds', category: 'Nuts' },
  { name: 'Walnuts', category: 'Nuts' },
  { name: 'Cashews', category: 'Nuts' },

  // Sauces & Condiments
  { name: 'Soy Sauce', category: 'Sauces' },
  { name: 'Mayonnaise', category: 'Sauces' },
  { name: 'Mustard', category: 'Sauces' },
  { name: 'Ketchup', category: 'Sauces' },
  { name: 'Hot Sauce', category: 'Sauces' },
  { name: 'Sriracha', category: 'Sauces' },
  { name: 'Miso Paste', category: 'Sauces' },
  { name: 'Tomato Paste', category: 'Sauces' },
  { name: 'Coconut Milk', category: 'Pantry' },
  { name: 'Chicken Broth', category: 'Pantry' },
  { name: 'Beef Broth', category: 'Pantry' },
  { name: 'Vegetable Broth', category: 'Pantry' },
];
