import { GenerateRecipeFromPantryOutput } from '@/ai/flows/generate-recipe-from-pantry';
import { AnalyzeRecipeNutritionOutput } from '@/ai/flows/analyze-recipe-nutrition-flow';

export type Recipe = GenerateRecipeFromPantryOutput & {
  id: string;
  nutrition?: AnalyzeRecipeNutritionOutput;
  imageUrl?: string;
  savedAt?: number;
};

export type Ingredient = {
  name: string;
  category: string;
};

export const COMMON_INGREDIENTS: Ingredient[] = [
  // Indian Staples & Spices
  { name: 'Basmati Rice', category: 'Indian Pantry' },
  { name: 'Paneer', category: 'Dairy' },
  { name: 'Ghee', category: 'Dairy' },
  { name: 'Curry Leaves', category: 'Herbs' },
  { name: 'Mustard Seeds', category: 'Spices' },
  { name: 'Fenugreek Seeds (Methi)', category: 'Spices' },
  { name: 'Asafoetida (Hing)', category: 'Spices' },
  { name: 'Tamarind Paste', category: 'Sauces' },
  { name: 'Garam Masala', category: 'Spices' },
  { name: 'Cardamom Pods', category: 'Spices' },
  { name: 'Cloves', category: 'Spices' },
  { name: 'Coriander Seeds', category: 'Spices' },
  { name: 'Cumin Seeds (Jeera)', category: 'Spices' },
  { name: 'Turmeric Powder', category: 'Spices' },
  { name: 'Red Chili Powder (Kashmiri)', category: 'Spices' },
  { name: 'Besan (Gram Flour)', category: 'Pantry' },
  { name: 'Moong Dal', category: 'Legumes' },
  { name: 'Toor Dal', category: 'Legumes' },
  { name: 'Chana Dal', category: 'Legumes' },
  { name: 'Urad Dal', category: 'Legumes' },
  { name: 'Kalonji (Nigella Seeds)', category: 'Spices' },
  { name: 'Amchur (Mango Powder)', category: 'Spices' },
  { name: 'Kasuri Methi', category: 'Herbs' },
  { name: 'Saffron', category: 'Spices' },
  { name: 'Star Anise', category: 'Spices' },
  { name: 'Mace (Javitri)', category: 'Spices' },
  { name: 'Black Salt (Kala Namak)', category: 'Spices' },

  // Grains & Flours
  { name: 'All-Purpose Flour', category: 'Pantry' },
  { name: 'Whole Wheat Flour (Atta)', category: 'Pantry' },
  { name: 'Bread Flour', category: 'Pantry' },
  { name: 'Cornmeal', category: 'Pantry' },
  { name: 'Quinoa', category: 'Pantry' },
  { name: 'Couscous', category: 'Pantry' },
  { name: 'Bulgur', category: 'Pantry' },
  { name: 'Arborio Rice', category: 'Pantry' },
  { name: 'Jasmine Rice', category: 'Pantry' },
  { name: 'Wild Rice', category: 'Pantry' },
  { name: 'Buckwheat', category: 'Pantry' },
  { name: 'Semolina', category: 'Pantry' },
  { name: 'Rolled Oats', category: 'Pantry' },

  // Vegetables - Root & Alliums
  { name: 'Onion', category: 'Vegetables' },
  { name: 'Red Onion', category: 'Vegetables' },
  { name: 'Shallots', category: 'Vegetables' },
  { name: 'Leeks', category: 'Vegetables' },
  { name: 'Garlic', category: 'Vegetables' },
  { name: 'Ginger', category: 'Vegetables' },
  { name: 'Potato', category: 'Vegetables' },
  { name: 'Sweet Potato', category: 'Vegetables' },
  { name: 'Carrot', category: 'Vegetables' },
  { name: 'Parsnip', category: 'Vegetables' },
  { name: 'Beetroot', category: 'Vegetables' },
  { name: 'Radish (Mooli)', category: 'Vegetables' },
  { name: 'Turnip', category: 'Vegetables' },
  { name: 'Galangal', category: 'Vegetables' },
  { name: 'Turmeric Root', category: 'Vegetables' },
  { name: 'Cassava', category: 'Vegetables' },
  { name: 'Yam', category: 'Vegetables' },
  { name: 'Taro', category: 'Vegetables' },
  { name: 'Lotus Root', category: 'Vegetables' },

  // Vegetables - Greens & Cruciferous
  { name: 'Spinach', category: 'Vegetables' },
  { name: 'Kale', category: 'Vegetables' },
  { name: 'Swiss Chard', category: 'Vegetables' },
  { name: 'Bok Choy', category: 'Vegetables' },
  { name: 'Cabbage', category: 'Vegetables' },
  { name: 'Red Cabbage', category: 'Vegetables' },
  { name: 'Napa Cabbage', category: 'Vegetables' },
  { name: 'Broccoli', category: 'Vegetables' },
  { name: 'Broccolini', category: 'Vegetables' },
  { name: 'Cauliflower', category: 'Vegetables' },
  { name: 'Brussels Sprouts', category: 'Vegetables' },
  { name: 'Asparagus', category: 'Vegetables' },
  { name: 'Artichoke', category: 'Vegetables' },
  { name: 'Celery', category: 'Vegetables' },
  { name: 'Fennel Bulb', category: 'Vegetables' },

  // Vegetables - Nightshades & Others
  { name: 'Tomato', category: 'Vegetables' },
  { name: 'Cherry Tomatoes', category: 'Vegetables' },
  { name: 'Eggplant', category: 'Vegetables' },
  { name: 'Thai Eggplant', category: 'Vegetables' },
  { name: 'Bell Pepper (Red)', category: 'Vegetables' },
  { name: 'Bell Pepper (Green)', category: 'Vegetables' },
  { name: 'Zucchini', category: 'Vegetables' },
  { name: 'Yellow Squash', category: 'Vegetables' },
  { name: 'Butternut Squash', category: 'Vegetables' },
  { name: 'Pumpkin', category: 'Vegetables' },
  { name: 'Okra (Bhindi)', category: 'Vegetables' },
  { name: 'Bitter Gourd (Karela)', category: 'Vegetables' },
  { name: 'Bottle Gourd (Lauki)', category: 'Vegetables' },
  { name: 'Drumstick (Moringa)', category: 'Vegetables' },
  { name: 'Green Beans', category: 'Vegetables' },
  { name: 'Snow Peas', category: 'Vegetables' },
  { name: 'Edamame', category: 'Vegetables' },

  // Chillies (Fresh)
  { name: 'Green Chilli', category: 'Spicy' },
  { name: 'Red Chilli', category: 'Spicy' },
  { name: 'Bird\'s Eye Chilli', category: 'Spicy' },
  { name: 'Jalapeño', category: 'Spicy' },
  { name: 'Habanero', category: 'Spicy' },
  { name: 'Serrano Pepper', category: 'Spicy' },
  { name: 'Poblano Pepper', category: 'Spicy' },
  { name: 'Ghost Pepper (Bhut Jolokia)', category: 'Spicy' },
  { name: 'Scotch Bonnet', category: 'Spicy' },

  // Mushrooms
  { name: 'Button Mushrooms', category: 'Fungi' },
  { name: 'Cremini Mushrooms', category: 'Fungi' },
  { name: 'Portobello Mushrooms', category: 'Fungi' },
  { name: 'Shiitake', category: 'Fungi' },
  { name: 'Oyster Mushrooms', category: 'Fungi' },
  { name: 'Enoki Mushrooms', category: 'Fungi' },
  { name: 'Porcini (Dried)', category: 'Fungi' },
  { name: 'Wood Ear Mushrooms', category: 'Fungi' },

  // Fruits
  { name: 'Lemon', category: 'Fruit' },
  { name: 'Lime', category: 'Fruit' },
  { name: 'Orange', category: 'Fruit' },
  { name: 'Apple', category: 'Fruit' },
  { name: 'Pear', category: 'Fruit' },
  { name: 'Mango', category: 'Fruit' },
  { name: 'Pineapple', category: 'Fruit' },
  { name: 'Avocado', category: 'Fruit' },
  { name: 'Pomegranate', category: 'Fruit' },
  { name: 'Coconut (Fresh)', category: 'Fruit' },
  { name: 'Tamarind (Fresh)', category: 'Fruit' },
  { name: 'Banana', category: 'Fruit' },
  { name: 'Plantain', category: 'Fruit' },

  // Proteins
  { name: 'Chicken Breast', category: 'Meat' },
  { name: 'Chicken Thighs', category: 'Meat' },
  { name: 'Whole Chicken', category: 'Meat' },
  { name: 'Lamb Leg', category: 'Meat' },
  { name: 'Lamb Mince', category: 'Meat' },
  { name: 'Beef Chuck', category: 'Meat' },
  { name: 'Beef Ribeye', category: 'Meat' },
  { name: 'Ground Beef', category: 'Meat' },
  { name: 'Pork Belly', category: 'Meat' },
  { name: 'Bacon', category: 'Meat' },
  { name: 'Salmon Fillet', category: 'Seafood' },
  { name: 'Tuna Steak', category: 'Seafood' },
  { name: 'Shrimp / Prawns', category: 'Seafood' },
  { name: 'Scallops', category: 'Seafood' },
  { name: 'Cod', category: 'Seafood' },
  { name: 'Tofu (Firm)', category: 'Proteins' },
  { name: 'Tofu (Silken)', category: 'Proteins' },
  { name: 'Tempeh', category: 'Proteins' },
  { name: 'Seitan', category: 'Proteins' },
  { name: 'Eggs', category: 'Fridge' },

  // Dairy & Alternatives
  { name: 'Milk', category: 'Dairy' },
  { name: 'Heavy Cream', category: 'Dairy' },
  { name: 'Sour Cream', category: 'Dairy' },
  { name: 'Greek Yogurt', category: 'Dairy' },
  { name: 'Butter (Unsalted)', category: 'Dairy' },
  { name: 'Butter (Salted)', category: 'Dairy' },
  { name: 'Cheddar Cheese', category: 'Dairy' },
  { name: 'Parmesan', category: 'Dairy' },
  { name: 'Mozzarella', category: 'Dairy' },
  { name: 'Feta', category: 'Dairy' },
  { name: 'Ricotta', category: 'Dairy' },
  { name: 'Mascarpone', category: 'Dairy' },
  { name: 'Goat Cheese', category: 'Dairy' },
  { name: 'Coconut Milk', category: 'Pantry' },
  { name: 'Almond Milk', category: 'Dairy' },
  { name: 'Soy Milk', category: 'Dairy' },

  // Oils & Vinegars
  { name: 'Extra Virgin Olive Oil', category: 'Oils' },
  { name: 'Vegetable Oil', category: 'Oils' },
  { name: 'Sesame Oil (Toasted)', category: 'Oils' },
  { name: 'Coconut Oil', category: 'Oils' },
  { name: 'Peanut Oil', category: 'Oils' },
  { name: 'Avocado Oil', category: 'Oils' },
  { name: 'Mustard Oil', category: 'Oils' },
  { name: 'Balsamic Vinegar', category: 'Vinegars' },
  { name: 'Apple Cider Vinegar', category: 'Vinegars' },
  { name: 'Rice Vinegar', category: 'Vinegars' },
  { name: 'Red Wine Vinegar', category: 'Vinegars' },
  { name: 'White Wine Vinegar', category: 'Vinegars' },

  // Sauces & Condiments
  { name: 'Soy Sauce', category: 'Sauces' },
  { name: 'Tamari', category: 'Sauces' },
  { name: 'Fish Sauce', category: 'Sauces' },
  { name: 'Oyster Sauce', category: 'Sauces' },
  { name: 'Worcestershire Sauce', category: 'Sauces' },
  { name: 'Sriracha', category: 'Spicy Sauces' },
  { name: 'Gochujang', category: 'Spicy Sauces' },
  { name: 'Harissa', category: 'Spicy Sauces' },
  { name: 'Sambal Oelek', category: 'Spicy Sauces' },
  { name: 'Miso Paste (White)', category: 'Sauces' },
  { name: 'Miso Paste (Red)', category: 'Sauces' },
  { name: 'Tahini', category: 'Sauces' },
  { name: 'Dijon Mustard', category: 'Sauces' },
  { name: 'Mayonnaise', category: 'Sauces' },
  { name: 'Ketchup', category: 'Sauces' },
  { name: 'Honey', category: 'Pantry' },
  { name: 'Maple Syrup', category: 'Pantry' },
  { name: 'Agave Nectar', category: 'Pantry' },

  // Nuts & Seeds
  { name: 'Almonds', category: 'Nuts & Seeds' },
  { name: 'Cashews', category: 'Nuts & Seeds' },
  { name: 'Walnuts', category: 'Nuts & Seeds' },
  { name: 'Pistachios', category: 'Nuts & Seeds' },
  { name: 'Peanuts', category: 'Nuts & Seeds' },
  { name: 'Pine Nuts', category: 'Nuts & Seeds' },
  { name: 'Sesame Seeds (White)', category: 'Nuts & Seeds' },
  { name: 'Sesame Seeds (Black)', category: 'Nuts & Seeds' },
  { name: 'Chia Seeds', category: 'Nuts & Seeds' },
  { name: 'Flax Seeds', category: 'Nuts & Seeds' },
  { name: 'Pumpkin Seeds (Pepitas)', category: 'Nuts & Seeds' },
  { name: 'Sunflower Seeds', category: 'Nuts & Seeds' },

  // Herbs (Fresh)
  { name: 'Cilantro (Coriander)', category: 'Herbs' },
  { name: 'Parsley (Flat-leaf)', category: 'Herbs' },
  { name: 'Basil (Genovese)', category: 'Herbs' },
  { name: 'Thai Basil', category: 'Herbs' },
  { name: 'Mint', category: 'Herbs' },
  { name: 'Rosemary', category: 'Herbs' },
  { name: 'Thyme', category: 'Herbs' },
  { name: 'Oregano', category: 'Herbs' },
  { name: 'Dill', category: 'Herbs' },
  { name: 'Chives', category: 'Herbs' },
  { name: 'Sage', category: 'Herbs' },
  { name: 'Lemongrass', category: 'Herbs' },
  { name: 'Bay Leaves', category: 'Herbs' },

  // Baking & Others
  { name: 'Baking Powder', category: 'Baking' },
  { name: 'Baking Soda', category: 'Baking' },
  { name: 'Yeast (Instant)', category: 'Baking' },
  { name: 'Vanilla Extract', category: 'Baking' },
  { name: 'Cocoa Powder', category: 'Baking' },
  { name: 'Dark Chocolate (70%)', category: 'Baking' },
  { name: 'Cornstarch', category: 'Baking' },
  { name: 'Gelatin Powder', category: 'Baking' },
];
